using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Library;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem;

public class CampaignPeriodicEventManager
{
	internal class PeriodicTicker<T>
	{
		private readonly List<T> _currentFrameToTickListFlattened;

		private bool _doParallel;

		private MBReadOnlyList<T> _list;

		private Action<T> _action;

		[SaveableProperty(1)]
		private double TickDebt
		{
			[MethodImpl(MethodImplOptions.NoInlining)]
			[CompilerGenerated]
			get
			{
				throw null;
			}
			[MethodImpl(MethodImplOptions.NoInlining)]
			[CompilerGenerated]
			set
			{
				throw null;
			}
		}

		[SaveableProperty(2)]
		private int Index
		{
			[MethodImpl(MethodImplOptions.NoInlining)]
			[CompilerGenerated]
			get
			{
				throw null;
			}
			[MethodImpl(MethodImplOptions.NoInlining)]
			[CompilerGenerated]
			set
			{
				throw null;
			}
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		internal PeriodicTicker()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		internal void Initialize(MBReadOnlyList<T> list, Action<T> action, bool doParallel)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		internal void PeriodicTickSome(double timeUnitsElapsed)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		public override string ToString()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			throw null;
		}
	}

	[SaveableField(120)]
	private PeriodicTicker<MobileParty> _mobilePartyHourlyTicker;

	[SaveableField(130)]
	private PeriodicTicker<MobileParty> _mobilePartyDailyTicker;

	[SaveableField(140)]
	private PeriodicTicker<MobileParty> _dailyTickPartyTicker;

	[SaveableField(150)]
	private PeriodicTicker<MobileParty> _hourlyTickMobilePartyTicker;

	[SaveableField(160)]
	private PeriodicTicker<Settlement> _hourlyTickSettlementTicker;

	[SaveableField(170)]
	private PeriodicTicker<Clan> _hourlyTickClanTicker;

	[SaveableField(180)]
	private PeriodicTicker<Town> _dailyTickTownTicker;

	[SaveableField(190)]
	private PeriodicTicker<Settlement> _dailyTickSettlementTicker;

	[SaveableField(200)]
	private PeriodicTicker<Hero> _dailyTickHeroTicker;

	[SaveableField(210)]
	private PeriodicTicker<Clan> _dailyTickClanTicker;

	[SaveableField(320)]
	private PeriodicTicker<MobileParty> _quarterDailyPartyTicker;

	[SaveableField(230)]
	private PeriodicTicker<MobileParty> _caravanMobilePartyPartialHourlyAiEventTicker;

	[SaveableField(250)]
	private PeriodicTicker<MobileParty> _garrisonMobilePartyPartialHourlyAiEventTicker;

	[SaveableField(260)]
	private PeriodicTicker<MobileParty> _militiaMobilePartyPartialHourlyAiEventTicker;

	[SaveableField(270)]
	private PeriodicTicker<MobileParty> _villagerMobilePartyPartialHourlyAiEventTicker;

	[SaveableField(280)]
	private PeriodicTicker<MobileParty> _customMobilePartyPartialHourlyAiEventTicker;

	[SaveableField(290)]
	private PeriodicTicker<MobileParty> _banditMobilePartyPartialHourlyAiEventTicker;

	[SaveableField(300)]
	private PeriodicTicker<MobileParty> _lordMobilePartyPartialHourlyAiEventTicker;

	[SaveableField(310)]
	private PeriodicTicker<MobileParty> _partiesWithoutPartyComponentsPartialHourlyAiEventTicker;

	[SaveableField(330)]
	private PeriodicTicker<MobileParty> _patrolPartyPartialHourlyAiEventTicker;

	private CampaignTime MinimumPeriodicEventInterval;

	private CampaignTime _lastGameTime;

	private double DeltaHours
	{
		[MethodImpl(MethodImplOptions.NoInlining)]
		get
		{
			throw null;
		}
	}

	private double DeltaDays
	{
		[MethodImpl(MethodImplOptions.NoInlining)]
		get
		{
			throw null;
		}
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal CampaignPeriodicEventManager()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	[LoadInitializationCallback]
	private void OnLoad(MetaData metaData)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal void InitializeTickers()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private MBList<Settlement> ShuffleSettlements()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal void TickPeriodicEvents()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PeriodicQuarterDailyTick()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal void MobilePartyHourlyTick()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal void TickPartialHourlyAi()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PeriodicHourlyTick()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PeriodicDailyTick()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public static MBCampaignEvent CreatePeriodicEvent(CampaignTime triggerPeriod, CampaignTime initialWait)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void DeleteMarkedPeriodicEvents()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal void OnTick(float dt)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void SignalPeriodicEvents()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static void AutoGeneratedStaticCollectObjectsCampaignPeriodicEventManager(object o, List<object> collectedObjects)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_mobilePartyHourlyTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_mobilePartyDailyTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_dailyTickPartyTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_hourlyTickMobilePartyTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_hourlyTickSettlementTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_hourlyTickClanTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_dailyTickTownTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_dailyTickSettlementTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_dailyTickHeroTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_dailyTickClanTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_quarterDailyPartyTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_caravanMobilePartyPartialHourlyAiEventTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_garrisonMobilePartyPartialHourlyAiEventTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_militiaMobilePartyPartialHourlyAiEventTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_villagerMobilePartyPartialHourlyAiEventTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_customMobilePartyPartialHourlyAiEventTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_banditMobilePartyPartialHourlyAiEventTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_lordMobilePartyPartialHourlyAiEventTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_partiesWithoutPartyComponentsPartialHourlyAiEventTicker(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_patrolPartyPartialHourlyAiEventTicker(object o)
	{
		throw null;
	}
}
