using System.Collections.Generic;
using System.Runtime.CompilerServices;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem;

internal class FactionManagerStancesData
{
	[SaveableField(10)]
	private Dictionary<(IFaction, IFaction), StanceLink> _stances;

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static void AutoGeneratedStaticCollectObjectsFactionManagerStancesData(object o, List<object> collectedObjects)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_stances(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public Dictionary<(IFaction, IFaction), StanceLink>.ValueCollection GetStanceLinks()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal StanceLink GetStance(IFaction faction1, IFaction faction2)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void AddStance(StanceLink stance)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void RemoveStance(StanceLink stance)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private (IFaction, IFaction) GetKey(IFaction faction1, IFaction faction2)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private (IFaction, IFaction) GetKey(StanceLink stance)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public FactionManagerStancesData()
	{
		throw null;
	}
}
