using System.ComponentModel;
using System.Numerics;
using System.Runtime.CompilerServices;
using TaleWorlds.Core.ViewModelCollection.ImageIdentifiers;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.ExtraWidgets;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Multiplayer;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Multiplayer.HUD;
using TaleWorlds.MountAndBlade.Multiplayer.ViewModelCollection;
using TaleWorlds.MountAndBlade.Multiplayer.ViewModelCollection.ClassLoadout;

namespace TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated0;

public class MultiplayerDeathCard__TaleWorlds_MountAndBlade_Multiplayer_ViewModelCollection_MPDeathCardVM : Widget, IGeneratedGauntletMovieRoot
{
	private Widget _widget;

	private MultiplayerDeathCardWidget _widget_0;

	private ListPanel _widget_0_0;

	private ListPanel _widget_0_0_0;

	private ListPanel _widget_0_0_0_0;

	private Widget _widget_0_0_0_0_0;

	private Widget _widget_0_0_0_0_0_0;

	private Widget _widget_0_0_0_0_0_0_0;

	private Widget _widget_0_0_0_0_0_0_0_0;

	private ImageIdentifierWidget _widget_0_0_0_0_0_0_0_1;

	private MultiplayerTroopTypeIconWidget _widget_0_0_0_0_0_0_1;

	private Widget _widget_0_0_0_0_0_0_1_0;

	private ListPanel _widget_0_0_0_0_1;

	private TextWidget _widget_0_0_0_0_1_0;

	private ScrollingRichTextWidget _widget_0_0_0_0_1_1;

	private TextWidget _widget_0_0_0_1;

	private Widget _widget_0_0_1;

	private ListPanel _widget_0_0_1_0;

	private TextWidget _widget_0_0_1_0_0;

	private TextWidget _widget_0_0_1_0_1;

	private Widget _widget_0_0_1_0_2;

	private TextWidget _widget_0_0_1_0_3;

	private ScrollingRichTextWidget _widget_0_0_1_0_4;

	private MPDeathCardVM _datasource_Root;

	private MPPlayerVM _datasource_Root_PlayerProperties;

	private MPTeammateCompassTargetVM _datasource_Root_PlayerProperties_CompassElement;

	private BannerImageIdentifierVM _datasource_Root_PlayerProperties_CompassElement_Banner;

	[MethodImpl(MethodImplOptions.NoInlining)]
	public MultiplayerDeathCard__TaleWorlds_MountAndBlade_Multiplayer_ViewModelCollection_MPDeathCardVM(UIContext context)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void CreateWidgets()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void SetIds()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void SetAttributes()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void RefreshBindingWithChildren()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void DestroyDataSource()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void SetDataSource(MPDeathCardVM dataSource)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_0(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_0_0_0_0_1_0(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_0_0_0_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_0_0_0_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_0_0_0_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_0_0_0_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_0_0_0_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_0_0_0_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_0_0_0_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_0_0_0_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_0_0_0_0_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_0_0_0_0_1_1(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_0_0_0_1(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_0_0_1_0_0(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_0_0_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_0_0_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_0_0_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_0_0_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_0_0_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_0_0_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_0_0_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_0_0_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_0_0_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_0_0_1_0_1(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_0_0_1_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_0_0_1_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_0_0_1_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_0_0_1_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_0_0_1_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_0_0_1_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_0_0_1_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_0_0_1_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_0_0_1_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_0_0_1_0_3(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_0_0_1_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_0_0_1_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_0_0_1_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_0_0_1_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_0_0_1_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_0_0_1_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_0_0_1_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_0_0_1_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_0_0_1_0_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_0_0_1_0_4(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_0_0_0_0_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_0_0_0_0_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_0_0_0_0_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_0_0_0_0_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_0_0_0_0_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_0_0_0_0_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_0_0_0_0_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_0_0_0_0_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_0_0_0_0_0_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_0_0_0_0_0_0_0_0(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_0_0_0_0_0_0_1(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_0_0_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_0_0_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_0_0_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_0_0_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_0_0_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_0_0_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_0_0_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_0_0_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_0_0_0_0_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_0_0_0_0_0_0_1_0(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_0_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_0_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_0_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_0_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_0_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_0_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_0_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_0_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_0_0_0_0_0_0_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_0_0_0_0_0_0_0_1(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedListenerOf_datasource_Root_PlayerProperties(object sender, PropertyChangedEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_PlayerProperties(object sender, PropertyChangedWithValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_PlayerProperties(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_PlayerProperties(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_PlayerProperties(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_PlayerProperties(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_PlayerProperties(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_PlayerProperties(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_PlayerProperties(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleViewModelPropertyChangeOf_datasource_Root_PlayerProperties(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedListenerOf_datasource_Root_PlayerProperties_CompassElement(object sender, PropertyChangedEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_PlayerProperties_CompassElement(object sender, PropertyChangedWithValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_PlayerProperties_CompassElement(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_PlayerProperties_CompassElement(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_PlayerProperties_CompassElement(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_PlayerProperties_CompassElement(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_PlayerProperties_CompassElement(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_PlayerProperties_CompassElement(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_PlayerProperties_CompassElement(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleViewModelPropertyChangeOf_datasource_Root_PlayerProperties_CompassElement(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedListenerOf_datasource_Root_PlayerProperties_CompassElement_Banner(object sender, PropertyChangedEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_PlayerProperties_CompassElement_Banner(object sender, PropertyChangedWithValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_PlayerProperties_CompassElement_Banner(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_PlayerProperties_CompassElement_Banner(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_PlayerProperties_CompassElement_Banner(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_PlayerProperties_CompassElement_Banner(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_PlayerProperties_CompassElement_Banner(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_PlayerProperties_CompassElement_Banner(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_PlayerProperties_CompassElement_Banner(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleViewModelPropertyChangeOf_datasource_Root_PlayerProperties_CompassElement_Banner(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void RefreshDataSource_datasource_Root(MPDeathCardVM newDataSource)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void RefreshDataSource_datasource_Root_PlayerProperties(MPPlayerVM newDataSource)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void RefreshDataSource_datasource_Root_PlayerProperties_CompassElement(MPTeammateCompassTargetVM newDataSource)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void RefreshDataSource_datasource_Root_PlayerProperties_CompassElement_Banner(BannerImageIdentifierVM newDataSource)
	{
		throw null;
	}
}
