using System.ComponentModel;
using System.Numerics;
using System.Runtime.CompilerServices;
using TaleWorlds.CampaignSystem.ViewModelCollection;
using TaleWorlds.Core.ViewModelCollection.Information;
using TaleWorlds.Core.ViewModelCollection.Selector;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.ExtraWidgets;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;

namespace SandBox.GauntletUI.AutoGenerated1;

public class CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_2_Standard_DropdownWithHorizontalControl__DependendPrefab : ListPanel
{
	private ListPanel _widget;

	private Widget _widget_0;

	private ButtonWidget _widget_0_0;

	private AnimatedDropdownWidget _widget_1;

	private Widget _widget_1_0;

	private ButtonWidget _widget_1_0_0;

	private ScrollingRichTextWidget _widget_1_0_0_0;

	private HintWidget _widget_1_0_0_1;

	private Widget _widget_1_0_1;

	private HintWidget _widget_1_0_1_0;

	private Widget _widget_1_1;

	private BrushWidget _widget_1_1_0;

	private ScrollablePanel _widget_1_1_0_0;

	private Widget _widget_1_1_0_0_0;

	private ListPanel _widget_1_1_0_0_0_0;

	private ScrollbarWidget _widget_1_1_0_1;

	private Widget _widget_1_1_0_1_0;

	private ImageWidget _widget_1_1_0_1_1;

	private Widget _widget_2;

	private ButtonWidget _widget_2_0;

	private CampaignOptionItemVM _datasource_Root;

	private CampaignOptionSelectorVM _datasource_Root_SelectionSelector;

	private MBBindingList<SelectorItemVM> _datasource_Root_SelectionSelector_ItemList;

	private HintViewModel _datasource_Root_Hint;

	[MethodImpl(MethodImplOptions.NoInlining)]
	public CampaignOptions__TaleWorlds_CampaignSystem_ViewModelCollection_CampaignOptionsVM_Dependency_2_Standard_DropdownWithHorizontalControl__DependendPrefab(UIContext context)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void CreateWidgets()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void SetIds()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void SetAttributes()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void DestroyDataSource()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void SetDataSource(CampaignOptionItemVM dataSource)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void EventListenerOf_widget_0_0(Widget widget, string commandName, object[] args)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void EventListenerOf_widget_1(Widget widget, string commandName, object[] args)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void EventListenerOf_widget_2_0(Widget widget, string commandName, object[] args)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void EventListenerOf_widget_1_0_0_1(Widget widget, string commandName, object[] args)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void EventListenerOf_widget_1_0_1_0(Widget widget, string commandName, object[] args)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_0_0(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_1_0_0(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_1_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_1_0_1(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_2_0(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectionSelector(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleViewModelPropertyChangeOf_datasource_Root_SelectionSelector(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedListenerOf_datasource_Root_Hint(object sender, PropertyChangedEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleViewModelPropertyChangeOf_datasource_Root_Hint(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void OnList_datasource_Root_SelectionSelector_ItemListChanged(object sender, ListChangedEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void RefreshDataSource_datasource_Root_SelectionSelector(CampaignOptionSelectorVM newDataSource)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void RefreshDataSource_datasource_Root_Hint(HintViewModel newDataSource)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void RefreshDataSource_datasource_Root_SelectionSelector_ItemList(MBBindingList<SelectorItemVM> newDataSource)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void RefreshDataSource_datasource_Root(CampaignOptionItemVM newDataSource)
	{
		throw null;
	}
}
