using System.Collections.Generic;
using System.Runtime.CompilerServices;
using TaleWorlds.CampaignSystem.GameMenus;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues;

public class BettingFraudIssueBehavior : CampaignBehaviorBase
{
	public class BettingFraudIssue : IssueBase
	{
		private const int NeededTournamentCount = 5;

		private const int IssueDuration = 45;

		private const int MainHeroSkillLimit = 50;

		private const int MainClanRenownLimit = 50;

		private const int RelationLimitWithIssueOwner = -10;

		private const float IssueOwnerPowerPenaltyForIssueEffect = -0.2f;

		public override TextObject IssueBriefByIssueGiver
		{
			[MethodImpl(MethodImplOptions.NoInlining)]
			get
			{
				throw null;
			}
		}

		public override TextObject IssueAcceptByPlayer
		{
			[MethodImpl(MethodImplOptions.NoInlining)]
			get
			{
				throw null;
			}
		}

		public override TextObject IssueQuestSolutionExplanationByIssueGiver
		{
			[MethodImpl(MethodImplOptions.NoInlining)]
			get
			{
				throw null;
			}
		}

		public override TextObject IssueQuestSolutionAcceptByPlayer
		{
			[MethodImpl(MethodImplOptions.NoInlining)]
			get
			{
				throw null;
			}
		}

		public override bool IsThereAlternativeSolution
		{
			[MethodImpl(MethodImplOptions.NoInlining)]
			get
			{
				throw null;
			}
		}

		public override bool IsThereLordSolution
		{
			[MethodImpl(MethodImplOptions.NoInlining)]
			get
			{
				throw null;
			}
		}

		public override TextObject Title
		{
			[MethodImpl(MethodImplOptions.NoInlining)]
			get
			{
				throw null;
			}
		}

		public override TextObject Description
		{
			[MethodImpl(MethodImplOptions.NoInlining)]
			get
			{
				throw null;
			}
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		internal static void AutoGeneratedStaticCollectObjectsBettingFraudIssue(object o, List<object> collectedObjects)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		public BettingFraudIssue(Hero issueOwner)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		protected override void OnGameLoad()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		protected override void HourlyTick()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		protected override QuestBase GenerateIssueQuest(string questId)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		public override IssueFrequency GetFrequency()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		protected override bool CanPlayerTakeQuestConditions(Hero issueOwner, out PreconditionFlags flag, out Hero relationHero, out SkillObject skill)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		public override bool IssueStayAliveConditions()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		protected override void CompleteIssueWithTimedOutConsequences()
		{
			throw null;
		}
	}

	public class BettingFraudQuest : QuestBase
	{
		private enum Directives
		{
			None = 0,
			LoseAt3RdRound = 2,
			LoseAt4ThRound = 3,
			WinTheTournament = 4
		}

		private enum AfterTournamentConversationState
		{
			None,
			SmallReward,
			BigReward,
			MinorOffense,
			SecondMinorOffense,
			MajorOffense
		}

		private const int TournamentFixCount = 5;

		private const int MinorOffensiveLimit = 2;

		private const int SmallReward = 250;

		private const int BigReward = 2500;

		private const int CounterOfferReward = 4500;

		private const string MaleThug = "betting_fraud_thug_male";

		private const string FemaleThug = "betting_fraud_thug_female";

		[SaveableField(100)]
		private JournalLog _startLog;

		[SaveableField(1)]
		private Hero _counterOfferNotable;

		[SaveableField(10)]
		internal readonly CharacterObject _thug;

		[SaveableField(20)]
		private int _fixedTournamentCount;

		[SaveableField(30)]
		private int _minorOffensiveCount;

		private Directives _currentDirective;

		private AfterTournamentConversationState _afterTournamentConversationState;

		private bool _counterOfferAccepted;

		private bool _readyToStartTournament;

		private bool _startTournamentEndConversation;

		[SaveableField(40)]
		private bool _counterOfferConversationDone;

		public override TextObject Title
		{
			[MethodImpl(MethodImplOptions.NoInlining)]
			get
			{
				throw null;
			}
		}

		public override bool IsRemainingTimeHidden
		{
			[MethodImpl(MethodImplOptions.NoInlining)]
			get
			{
				throw null;
			}
		}

		private TextObject StartLog
		{
			[MethodImpl(MethodImplOptions.NoInlining)]
			get
			{
				throw null;
			}
		}

		private TextObject CurrentDirectiveLog
		{
			[MethodImpl(MethodImplOptions.NoInlining)]
			get
			{
				throw null;
			}
		}

		private TextObject QuestFailedWithTimeOutLog
		{
			[MethodImpl(MethodImplOptions.NoInlining)]
			get
			{
				throw null;
			}
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		internal static void AutoGeneratedStaticCollectObjectsBettingFraudQuest(object o, List<object> collectedObjects)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		internal static object AutoGeneratedGetMemberValue_thug(object o)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		internal static object AutoGeneratedGetMemberValue_startLog(object o)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		internal static object AutoGeneratedGetMemberValue_counterOfferNotable(object o)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		internal static object AutoGeneratedGetMemberValue_fixedTournamentCount(object o)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		internal static object AutoGeneratedGetMemberValue_minorOffensiveCount(object o)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		internal static object AutoGeneratedGetMemberValue_counterOfferConversationDone(object o)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		public BettingFraudQuest(string questId, Hero questGiver, CampaignTime duration, int rewardGold)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		protected override void InitializeQuestOnGameLoad()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		protected override void HourlyTick()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void SelectCounterOfferNotable(Settlement settlement)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void IncreaseMinorOffensive()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void IncreaseFixedTournamentCount()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void SetCurrentDirective()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void StartTournamentMission()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		protected override void RegisterEvents()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void OnPlayerEliminatedFromTournament(int round, Town town)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void OnTournamentFinished(CharacterObject winner, MBReadOnlyList<CharacterObject> participants, Town town, ItemObject prize)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void OnGameMenuOpened(MenuCallbackArgs args)
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		protected override void OnTimedOut()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		protected override void SetDialogs()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private DialogFlow GetOfferDialogFlow()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void OfferDialogFlowConsequence()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private DialogFlow GetDiscussDialogFlow()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private bool DiscussDialogCondition()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private bool NpcTournamentLocationCondition()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private DialogFlow GetDialogWithThugStart()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private bool DialogWithThugStartCondition()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private bool PositiveOptionCondition()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void PositiveOptionConsequences()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private bool NegativeOptionCondition()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void NegativeOptionConsequence()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private TextObject GetDirectiveText()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private DialogFlow GetDialogWithThugEnd()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private bool DialogWithThugEndCondition()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void DialogWithThugEndConsequence()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private DialogFlow GetCounterOfferDialog()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private bool CounterOfferConversationStartCondition()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void CounterOfferConversationStartConsequence()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private bool AccusationCondition()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void CounterOfferAcceptedConsequence()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void MainHeroSuccessfullyFixedTournaments()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void MainHeroFailToFixTournaments()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void MainHeroChooseNotToFixTournaments()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void MainHeroAcceptsCounterOffer()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private void PlayerDidNotCompleteTournaments()
		{
			throw null;
		}
	}

	public class BettingFraudIssueTypeDefiner : SaveableTypeDefiner
	{
		[MethodImpl(MethodImplOptions.NoInlining)]
		public BettingFraudIssueTypeDefiner()
		{
			throw null;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		protected override void DefineClassTypes()
		{
			throw null;
		}
	}

	private const IssueBase.IssueFrequency BettingFraudIssueFrequency = IssueBase.IssueFrequency.Rare;

	private const string JoinTournamentMenuId = "menu_town_tournament_join";

	private const string JoinTournamentForBettingFraudQuestMenuId = "menu_town_tournament_join_betting_fraud";

	private const int SettlementSecurityLimit = 50;

	private BettingFraudQuest _cachedQuest;

	private static BettingFraudQuest Instance
	{
		[MethodImpl(MethodImplOptions.NoInlining)]
		get
		{
			throw null;
		}
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public override void RegisterEvents()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void OnSessionLaunched(CampaignGameStarter gameStarter)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void game_menu_tournament_join_on_init(MenuCallbackArgs args)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void game_menu_tournament_join_current_game_on_consequence(MenuCallbackArgs args)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	[GameMenuInitializationHandler("menu_town_tournament_join_betting_fraud")]
	private static void game_menu_ui_town_ui_on_init(MenuCallbackArgs args)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public override void SyncData(IDataStore dataStore)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void CheckForIssue(Hero hero)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private bool ConditionsHold(Hero issueGiver)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private IssueBase OnStartIssue(in PotentialIssueData pid, Hero issueOwner)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public BettingFraudIssueBehavior()
	{
		throw null;
	}
}
