using System.Collections.Generic;
using System.Runtime.CompilerServices;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;

namespace TaleWorlds.CampaignSystem.TournamentGames;

public class FightTournamentGame : TournamentGame
{
	private const int LordLimitForEliteReward = 4;

	private const int EliteRewardLordCountToDivideRewards = 10;

	private const int EliteRewardGroupCount = 2;

	private const int RegularRewardMinimumValue = 1600;

	private const int RegularRewardMaximumValue = 5000;

	private const int ParticipateTournamentMinimumSkillLimit = 100;

	private const float RegularBannerRewardChance = 0.05f;

	public const int ParticipantTroopMinimumTierLimit = 3;

	private MBList<ItemObject> _possibleBannerRewardItemObjectsCache;

	private MBList<ItemObject> _possibleRegularRewardItemObjectsCache;

	private MBList<ItemObject> _possibleEliteRewardItemObjectsCache;

	public override int MaxTeamSize
	{
		[MethodImpl(MethodImplOptions.NoInlining)]
		get
		{
			throw null;
		}
	}

	public override int MaxTeamNumberPerMatch
	{
		[MethodImpl(MethodImplOptions.NoInlining)]
		get
		{
			throw null;
		}
	}

	public override int RemoveTournamentAfterDays
	{
		[MethodImpl(MethodImplOptions.NoInlining)]
		get
		{
			throw null;
		}
	}

	public override int MaximumParticipantCount
	{
		[MethodImpl(MethodImplOptions.NoInlining)]
		get
		{
			throw null;
		}
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static void AutoGeneratedStaticCollectObjectsFightTournamentGame(object o, List<object> collectedObjects)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public FightTournamentGame(Town town)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public override bool CanBeAParticipant(CharacterObject character, bool considerSkills)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public override TextObject GetMenuText()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public override void OpenMission(Settlement settlement, bool isPlayerParticipating)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public override MBList<CharacterObject> GetParticipantCharacters(Settlement settlement, bool includePlayer = true)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private bool CanNpcJoinTournament(Hero hero, MBList<CharacterObject> participantCharacters, bool considerSkills)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void GetUpgradeTargets(CharacterObject troop, ref List<CharacterObject> list)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void SortTournamentParticipants(MBList<CharacterObject> participantCharacters)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private int GetTroopPriorityPointForTournament(CharacterObject troop)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	protected override ItemObject GetTournamentPrize(bool includePlayer, int lastRecordedLordCountForTournamentPrize)
	{
		throw null;
	}
}
