using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.CompilerServices;
using TaleWorlds.SaveSystem.Resolvers;

namespace TaleWorlds.SaveSystem.Definition;

public class DefinitionContext
{
	private Dictionary<Type, TypeDefinition> _rootClassDefinitions;

	private Dictionary<Type, TypeDefinition> _classDefinitions;

	private Dictionary<SaveId, TypeDefinition> _classDefinitionsWithId;

	private Dictionary<Type, InterfaceDefinition> _interfaceDefinitions;

	private Dictionary<SaveId, InterfaceDefinition> _interfaceDefinitionsWithId;

	private Dictionary<Type, EnumDefinition> _enumDefinitions;

	private Dictionary<SaveId, EnumDefinition> _enumDefinitionsWithId;

	private Dictionary<Type, ContainerDefinition> _containerDefinitions;

	private Dictionary<SaveId, ContainerDefinition> _containerDefinitionsWithId;

	private Dictionary<Type, GenericTypeDefinition> _genericClassDefinitions;

	private Dictionary<Type, StructDefinition> _structDefinitions;

	private Dictionary<SaveId, StructDefinition> _structDefinitionsWithId;

	private Dictionary<Type, GenericTypeDefinition> _genericStructDefinitions;

	private Dictionary<Type, BasicTypeDefinition> _basicTypeDefinitions;

	private Dictionary<SaveId, BasicTypeDefinition> _basicTypeDefinitionsWithId;

	private Dictionary<Type, TypeDefinitionBase> _allTypeDefinitions;

	private Dictionary<SaveId, TypeDefinitionBase> _allTypeDefinitionsWithId;

	private Dictionary<SaveId, IConflictResolver> _conflictResolvers;

	private Dictionary<TypeDefinitionBase, IConflictResolver> _conflictResolversWithType;

	private List<IAutoGeneratedSaveManager> _autoGeneratedSaveManagers;

	private Assembly[] _assemblies;

	public List<string> _errors;

	private List<SaveableTypeDefiner> _saveableTypeDefiners;

	public bool GotError
	{
		[MethodImpl(MethodImplOptions.NoInlining)]
		get
		{
			throw null;
		}
	}

	public IEnumerable<string> Errors
	{
		[MethodImpl(MethodImplOptions.NoInlining)]
		get
		{
			throw null;
		}
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public DefinitionContext()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal void AddRootClassDefinition(TypeDefinition rootClassDefinition)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal void AddClassDefinition(TypeDefinition classDefinition)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal void AddStructDefinition(StructDefinition structDefinition)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal void AddInterfaceDefinition(InterfaceDefinition interfaceDefinition)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal void AddEnumDefinition(EnumDefinition enumDefinition)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal void AddContainerDefinition(ContainerDefinition containerDefinition)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal void AddBasicTypeDefinition(BasicTypeDefinition basicTypeDefinition)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal void AddConflictResolver(TypeSaveId saveId, IConflictResolver conflictResolver)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal bool GetConflictedFieldMemberTypeId(TypeDefinitionBase typeDefinition, ref MemberTypeId memberTypeId)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal bool GetConflictedPropertyMemberTypeId(TypeDefinitionBase typeDefinition, ref MemberTypeId memberTypeId)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void AddGenericClassDefinition(GenericTypeDefinition genericClassDefinition)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void AddGenericStructDefinition(GenericTypeDefinition genericStructDefinition)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void FillWithCurrentTypes()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private Assembly[] GetSaveableAssemblies()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void CollectTypes(Assembly assembly)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal TypeDefinitionBase GetTypeDefinition(Type type)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal TypeDefinition GetClassDefinition(Type type)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public TypeDefinitionBase TryGetTypeDefinition(SaveId saveId)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal GenericTypeDefinition ConstructGenericClassDefinition(Type type)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal bool HasDefinition(Type type)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal ContainerDefinition ConstructContainerDefinition(Type type, Assembly definedAssembly)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private Type ConstructTypeFrom(TypeDefinition baseClassDefinition, TypeDefinitionBase[] parameterDefinitions)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal TypeDefinition GetStructDefinition(Type type)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal InterfaceDefinition GetInterfaceDefinition(Type type)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal EnumDefinition GetEnumDefinition(Type type)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal ContainerDefinition GetContainerDefinition(Type type)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal GenericTypeDefinition ConstructGenericStructDefinition(Type type)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal BasicTypeDefinition GetBasicTypeDefinition(Type type)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void FindAutoGeneratedSaveManagers()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void InitializeAutoGeneratedSaveManagers()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void GenerateCode(SaveCodeGenerationContext context)
	{
		throw null;
	}
}
