using System.ComponentModel;
using System.Numerics;
using System.Runtime.CompilerServices;
using TaleWorlds.CampaignSystem.ViewModelCollection.ClanManagement;
using TaleWorlds.CampaignSystem.ViewModelCollection.ClanManagement.Categories;
using TaleWorlds.Core.ViewModelCollection.Information;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Party;

namespace SandBox.GauntletUI.AutoGenerated0;

public class ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_15_ClanPartiesLeftPanel__DependendPrefab : BrushListPanel
{
	private BrushListPanel _widget;

	private NavigationScopeTargeter _widget_0;

	private ListPanel _widget_1;

	private SortButtonWidget _widget_1_0;

	private TextWidget _widget_1_0_0;

	private BrushWidget _widget_1_0_0_0;

	private SortButtonWidget _widget_1_1;

	private TextWidget _widget_1_1_0;

	private BrushWidget _widget_1_1_0_0;

	private SortButtonWidget _widget_1_2;

	private TextWidget _widget_1_2_0;

	private BrushWidget _widget_1_2_0_0;

	private Widget _widget_1_3;

	private ListPanel _widget_2;

	private ScrollablePanel _widget_2_0;

	private NavigationScopeTargeter _widget_2_0_0;

	private Widget _widget_2_0_1;

	private NavigatableListPanel _widget_2_0_1_0;

	private NavigationAutoScrollWidget _widget_2_0_1_0_0;

	private ScrollablePanelFixedHeaderWidget _widget_2_0_1_0_1;

	private NavigatableListPanel _widget_2_0_1_0_2;

	private BrushWidget _widget_2_0_1_0_3;

	private HintWidget _widget_2_0_1_0_3_0;

	private ButtonWidget _widget_2_0_1_0_3_1;

	private TextWidget _widget_2_0_1_0_3_1_0;

	private NavigationAutoScrollWidget _widget_2_0_1_0_4;

	private ScrollablePanelFixedHeaderWidget _widget_2_0_1_0_5;

	private NavigatableListPanel _widget_2_0_1_0_6;

	private NavigationAutoScrollWidget _widget_2_0_1_0_7;

	private ScrollablePanelFixedHeaderWidget _widget_2_0_1_0_8;

	private NavigatableListPanel _widget_2_0_1_0_9;

	private PartyHeaderToggleWidget _widget_2_0_2;

	private ListPanel _widget_2_0_2_0;

	private BrushWidget _widget_2_0_2_0_0;

	private TextWidget _widget_2_0_2_0_1;

	private PartyHeaderToggleWidget _widget_2_0_3;

	private ListPanel _widget_2_0_3_0;

	private BrushWidget _widget_2_0_3_0_0;

	private TextWidget _widget_2_0_3_0_1;

	private PartyHeaderToggleWidget _widget_2_0_4;

	private ListPanel _widget_2_0_4_0;

	private BrushWidget _widget_2_0_4_0_0;

	private TextWidget _widget_2_0_4_0_1;

	private ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_42_Standard_VerticalScrollbar__DependendPrefab _widget_2_1;

	private ClanPartiesVM _datasource_Root;

	private ClanPartiesSortControllerVM _datasource_Root_SortController;

	private MBBindingList<ClanPartyItemVM> _datasource_Root_Parties;

	private HintViewModel _datasource_Root_CreateNewPartyActionHint;

	private MBBindingList<ClanPartyItemVM> _datasource_Root_Caravans;

	private MBBindingList<ClanPartyItemVM> _datasource_Root_Garrisons;

	[MethodImpl(MethodImplOptions.NoInlining)]
	public ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_15_ClanPartiesLeftPanel__DependendPrefab(UIContext context)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void CreateWidgets()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void SetIds()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void SetAttributes()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void DestroyDataSource()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void SetDataSource(ClanPartiesVM dataSource)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void EventListenerOf_widget_2_0_1_0_3_1(Widget widget, string commandName, object[] args)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void EventListenerOf_widget_1_0(Widget widget, string commandName, object[] args)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void EventListenerOf_widget_1_1(Widget widget, string commandName, object[] args)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void EventListenerOf_widget_1_2(Widget widget, string commandName, object[] args)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void EventListenerOf_widget_2_0_1_0_3_0(Widget widget, string commandName, object[] args)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_2_0_1_0_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_2_0_1_0_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_2_0_1_0_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_2_0_1_0_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_2_0_1_0_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_2_0_1_0_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_2_0_1_0_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_2_0_1_0_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_2_0_1_0_3_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_2_0_1_0_3_1(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_2_0_1_0_3_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_2_0_1_0_3_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_2_0_1_0_3_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_2_0_1_0_3_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_2_0_1_0_3_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_2_0_1_0_3_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_2_0_1_0_3_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_2_0_1_0_3_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_2_0_1_0_3_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_2_0_1_0_3_1_0(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_2_0_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_2_0_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_2_0_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_2_0_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_2_0_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_2_0_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_2_0_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_2_0_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_2_0_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_2_0_2_0_1(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_2_0_3_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_2_0_3_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_2_0_3_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_2_0_3_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_2_0_3_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_2_0_3_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_2_0_3_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_2_0_3_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_2_0_3_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_2_0_3_0_1(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_2_0_4_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_2_0_4_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_2_0_4_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_2_0_4_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_2_0_4_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_2_0_4_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_2_0_4_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_2_0_4_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_2_0_4_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_2_0_4_0_1(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_1_0(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_1_0_0(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_1_1(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_1_1_0(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_1_2(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void PropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void boolPropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void floatPropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vec2PropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void Vector2PropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void doublePropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void intPropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void uintPropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ColorPropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleWidgetPropertyChangeOf_widget_1_2_0(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedListenerOf_datasource_Root_SortController(object sender, PropertyChangedEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SortController(object sender, PropertyChangedWithValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SortController(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SortController(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SortController(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SortController(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SortController(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SortController(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SortController(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleViewModelPropertyChangeOf_datasource_Root_SortController(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedListenerOf_datasource_Root_CreateNewPartyActionHint(object sender, PropertyChangedEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CreateNewPartyActionHint(object sender, PropertyChangedWithValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CreateNewPartyActionHint(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CreateNewPartyActionHint(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CreateNewPartyActionHint(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CreateNewPartyActionHint(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CreateNewPartyActionHint(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CreateNewPartyActionHint(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CreateNewPartyActionHint(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void HandleViewModelPropertyChangeOf_datasource_Root_CreateNewPartyActionHint(string propertyName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void OnList_datasource_Root_PartiesChanged(object sender, ListChangedEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void OnList_datasource_Root_CaravansChanged(object sender, ListChangedEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public void OnList_datasource_Root_GarrisonsChanged(object sender, ListChangedEventArgs e)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void RefreshDataSource_datasource_Root(ClanPartiesVM newDataSource)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void RefreshDataSource_datasource_Root_SortController(ClanPartiesSortControllerVM newDataSource)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void RefreshDataSource_datasource_Root_Parties(MBBindingList<ClanPartyItemVM> newDataSource)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void RefreshDataSource_datasource_Root_CreateNewPartyActionHint(HintViewModel newDataSource)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void RefreshDataSource_datasource_Root_Caravans(MBBindingList<ClanPartyItemVM> newDataSource)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	private void RefreshDataSource_datasource_Root_Garrisons(MBBindingList<ClanPartyItemVM> newDataSource)
	{
		throw null;
	}
}
