using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace TaleWorlds.DotNet.AutoGenerated;

internal class SizeChecker
{
	[MethodImpl(MethodImplOptions.NoInlining)]
	[Conditional("_RGL_KEEP_ASSERTS")]
	private static void CheckTypeSizeAux(int managedSize, string name)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	[Conditional("_RGL_KEEP_ASSERTS")]
	private static void CheckTypeOffsetAux(IntPtr managedOffset, string className, string memberName)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	[Conditional("_RGL_KEEP_ASSERTS")]
	public static void CheckSharedStructureSizes()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	[Conditional("_RGL_KEEP_ASSERTS")]
	public static void CheckSharedStructureOffsets()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public SizeChecker()
	{
		throw null;
	}
}
