using System.Collections.Generic;
using System.Runtime.CompilerServices;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries;

public class ClanChangeKingdomLogEntry : LogEntry, IChatNotification, IWarLog
{
	[SaveableField(150)]
	public readonly Clan Clan;

	[SaveableField(151)]
	public readonly Kingdom OldKingdom;

	[SaveableField(152)]
	public readonly Kingdom NewKingdom;

	[SaveableField(153)]
	private readonly bool _byRebellion;

	public bool IsVisibleNotification
	{
		[MethodImpl(MethodImplOptions.NoInlining)]
		get
		{
			throw null;
		}
	}

	public override ChatNotificationType NotificationType
	{
		[MethodImpl(MethodImplOptions.NoInlining)]
		get
		{
			throw null;
		}
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static void AutoGeneratedStaticCollectObjectsClanChangeKingdomLogEntry(object o, List<object> collectedObjects)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValueClan(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValueOldKingdom(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValueNewKingdom(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	internal static object AutoGeneratedGetMemberValue_byRebellion(object o)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public ClanChangeKingdomLogEntry(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, bool byRebellion)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public bool IsRelatedToWar(StanceLink stance, out IFaction effector, out IFaction effected)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public TextObject GetNotificationText()
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public override ImportanceEnum GetImportanceForClan(Clan clan)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public override void GetConversationScoreAndComment(Hero talkTroop, bool findString, out string comment, out ImportanceEnum score)
	{
		throw null;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	public override string ToString()
	{
		throw null;
	}
}
